version: '3.7'

services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - '${LOCAL_POSTGRESQL_EXPOSED_PORT}:5432'
    volumes:
      - postgres:/data/postgres
    env_file:
      - .postgresql.env

volumes:
  postgres:
