name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Build the Docker image
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.GITHUB_USERNAME }}
        key: ${{ secrets.SERVER_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        script: |
          cd nestjs-github-ci
          git pull
          git status
